tasks/omnichain.ts, templates/messaging/tasks/deploy.ts.hbs, templates/messaging/tasks/interact.ts.hbs, templates/omnichain/contracts/{{contractName}}.sol.hbs, templates/omnichain/tasks/deploy.ts.hbs, templates/omnichain/tasks/interact.ts.hbs
* refactor the omnichain template gen
* improved the omnichain template to work with Athens 3 libs
=> fix: templates

tasks/verify.ts
This should make the `verify` task compatible with Athens 3.
=> fix: use the new URL for verify

tasks/balances.ts
Fixes an error when you tried querying a balance of an address and you didn't have a private key defined:
```
npx hardhat balances --address 0xa168cCF5dBDA0f32819f5F2822eF4437d8a962Ba
An unexpected error occurred:
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
at new NodeError (node:internal/errors:399:5)
at Function.from (node:buffer:335:9)
at bitcoinAddress (/Users/fadeev/github.com/zeta-chain/toolkit/lib/bitcoinAddress.ts:9:44)
at SimpleTaskDefinition.main [as action] (/Users/fadeev/github.com/zeta-chain/toolkit/tasks/balances.ts:145:22)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Environment._runTaskDefinition …
```
=> fix(balances): error when requesting a balances of a specific address when private key is undefined

helpers/fees.ts, tasks/fees.ts, tasks/index.ts
```
npx hardhat fees
Omnichain fees (in native gas tokens of destination chain):
┌────────────────┬────────────────────────┬────────────────────────┬────────────────────────┐
│    (index)     │        totalFee        │         gasFee         │      protocolFee       │
├────────────────┼────────────────────────┼────────────────────────┼────────────────────────┤
│  btc_testnet   │ '0.000000000000100000' │ '0.000000000000100000' │ '0.000000000000000000' │
│  bsc_testnet   │ '0.000105000000000000' │ '0.000105000000000000' │ '0.000000000000000000' │
│ mumbai_testnet │ '0.000030973009137000' │ '0.000030973009137000' │ '0.000000000000000000' │
│ goerli_testnet │ '0.000000000022680000' │ '0.000000000022680000' │ '0.000000000000000000' │
└────────────────┴────────────────────────┴────────────────── …
```
=> feat: Hardhat task to fetch CCM and zEVM fees

templates/omnichain/contracts/{{contractName}}.sol.hbs
Added `zContext calldata context` to the template.
Context: https://github.com/zeta-chain/node/pull/912
=> feat: update onCrossChainCall with zContext

package.json, yarn.lock
This includes a version of a faucet that fixes an issue with `hardhat console`: https://github.com/zeta-chain/zeta-apps/pull/1067
closes https://github.com/zeta-chain/toolkit/issues/31
=> chore: update faucet-cli version

lib/index.ts, tasks/messaging.ts, templates/messaging/tasks/interact.ts.hbs
```
npx hardhat messaging Hello a1:int a2:address a3:bool a4:bytes32 a5 a6:something
```
Produces the following contract:
```solidity
import "@openzeppelin/contracts/interfaces/IERC20.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@zetachain/protocol-contracts/contracts/evm/tools/ZetaInteractor.sol";
import "@zetachain/protocol-contracts/contracts/evm/interfaces/ZetaInterfaces.sol";
interface HelloErrors {
error InvalidMessageType();
}
contract Hello is
ZetaInteractor,
ZetaReceiver,
HelloErrors
{
bytes32 public constant HELLO_MESSAGE_TYPE =
keccak256("CROSS_CHAIN_HELLO");
event HelloEvent(int, address, bool, bytes32, bytes32, bytes32);
event HelloRevertedEvent(int, address, bool, bytes32, bytes32, bytes32); …
```
=> feat(templating): support types in ccm interact task

lib/index.ts, templates/messaging/contracts/{{contractName}}.sol.hbs, templates/omnichain/contracts/{{contractName}}.sol.hbs
* Using `string` as default type for both CCM and omnichain
* When creating a contract genrate `string memory` where appropriate.
This what gets generated:
```
npx hardhat omnichain MyOmnichainContract sometext
```
```solidity
import "@zetachain/protocol-contracts/contracts/zevm/SystemContract.sol";
import "@zetachain/protocol-contracts/contracts/zevm/interfaces/zContract.sol";
contract MyOmnichainContract is zContract {
error SenderNotSystemContract();
SystemContract public immutable systemContract;
constructor(address systemContractAddress) {
systemContract = SystemContract(systemContractAddress);
}
function onCrossChainCall(
zContext calldata context,
address zrc20,
uint256 amount,
bytes calldata message
) external virtual override …
```
=> fix(templating): use string as the default type

templates/omnichain/tasks/deploy.ts.hbs
Without error handling it could be confusing, because Hardhat is throwing `TypeError: Cannot read properties of undefined (reading 'address')`, which is unclear.
=> refactor(deploy): handle an error when a private key is not found

helpers/fees.ts
The HTTP has changed: https://github.com/zeta-chain/node/pull/846
Before:
```
npx hardhat fees
Omnichain fees (in native gas tokens of destination chain):
┌────────────────┬────────────────────────┬────────────────────────┬────────────────────────┐
│    (index)     │        totalFee        │         gasFee         │      protocolFee       │
├────────────────┼────────────────────────┼────────────────────────┼────────────────────────┤
│ mumbai_testnet │ '0.010031500000378000' │ '0.000031500000378000' │ '0.010000000000000000' │
│ goerli_testnet │ '0.000000009798159000' │ '0.000000009798159000' │ '0.000000000000000000' │
│  bsc_testnet   │ '0.250105000000000022' │ '0.000105000000000000' │ '0.250000000000000000' │
│  btc_testnet   │ '0.000000000000100000' │ '0.000000000000100000' │ …
```
=> fix(fees): query gas fees by chain ID

helpers/tx.ts, tasks/cctx.ts
* Shows how many CCTXs are pending in front of the one you're tracking
* Replaced BlockPI with ZetaChain's own WSS, because the former one was closing connection after 1 block (decided not to make a reconnecting socket for now)
* Added `--json` for non-interactive use
* Checks a tx on the destination chain. Currently not used in the UI, but this is good to have for integration testing: broadcast a tx, then run `npx hardhat cctx --json` and read the output to check that the CCTX has been successfully processed on the destination chain.
```
npx hardhat cctx 0xe6cac4dc7b978806bdd37262f3253289fb8a160a855275faf28a5196aa5ba4a9
✓ CCTXs on ZetaChain found.
✓ 0x0967302e138ad26abf9a4f40c2bd6c234324f650db2b4b50f39332d230c64fb4: 80001 → 7001: OutboundMined (Remote omnichain contract call completed)
✓ …
```
=>  feat(cctx): accept both inbound and cctx hash

contracts/BytesHelperLib.sol
The function is used to get a Bitcoin address when sending it in an omnichain contract `message`. Used in:
https://github.com/zeta-chain/example-contracts/blob/abb7a57deea783ab17f4c8295ececdf4a239bfc2/omnichain/staking/contracts/Staking.sol#L48-L58
=> feat: added `bytesToBech32Bytes` helper function

helpers/tx.ts
* Replaced WebSockets with periodic polling, now more reliable.
* Added conditional to handle cases where API doesn't return the expected result
```
npx hardhat cctx 0x86a07a9a0c0b0514c48fd7cf5dd70aff48c28fc2b5242bc07ad43e0c68e94fc0
✓ CCTXs on ZetaChain found.
✓ 0x91330792b0473a4d957d853728088fcc71f794b015abbf876de4d51900ca471d: 5 → 7001: OutboundMined (Remote omnichain contract call completed)
⠇ 0x751e652ceda8eac727ff44af38fc8932008d28ca6f82a309ac3f43475277ad52: 7001 → 80001 (1 in queue): PendingOutbound 
```
=> fix(cctx): prevent tracking from exiting before the cctx is finalized

tasks/balances.ts
Useful for CI integration testing.
=> feat(balances): add JSON flag

helpers/pools.ts, tasks/balances.ts, tasks/pools.ts
* added pair contract address in the output of `pools`:
```
npx hardhat pools    
┌─────────────────────┬──────────┬──────────┬──────────────────────────────────────────────┐
│       (index)       │   ZETA   │  ZRC-20  │                   Contract                   │
├─────────────────────┼──────────┼──────────┼──────────────────────────────────────────────┤
│       tMATIC        │ '240.09' │ '656.67' │ '0x4E77A430a1b8E9055540b2A4aB8364E4E31089ae' │
│        tBTC         │  '0.00'  │ '33.89'  │ '0xaDA812aCAB31a8646d234715E7B9947015f9ab62' │
│        tBNB         │ '884.44' │ '138.58' │ '0x16Ef1b018026E389FDA93c1e993E987CF6E852E7' │
│        gETH         │ '788.26' │ '102.68' │ '0x0C0B35C5eF00d9caD8D2ce65b147ea2A27d526Bc' │
│ USDC-mumbai_testnet │  '0.00'  │  '0.00'  │ …
```
=> feat(pools): display pair contract address

contracts/BytesHelperLib.sol
Sometimes this function is useful, for example, when storing recipient's address in memory bytes and then converting it to address when transferring: https://github.com/zeta-chain/example-contracts/pull/96
=> feat: bytesMemoryToAddress helper function

packages/tasks/src/index.ts, packages/tasks/src/tokens.ts
```
npx hardhat tokens
```
This is useful, because some tutorials expect ZRC-20 address as input when interacting. Having the interact task interpret something like "BNB.BSC" and turn it into an address is possible, but then the user needs to know the list of supported tokens. Copying it from the output of the tokens command seems like a good solution.
=> feat: `tokens` Hardhat task

packages/client/src/getFees.ts
Bitcoin is mistakingly shown in the output of `getFees` (because it's in the supported chains list). This removes Bitcoin as you can't send messages to and from Bitcoin.
=> fix: remove Bitcoin from getFees

packages/tasks/templates/messaging/tasks/deploy.ts.hbs
* Removed `zetaTokenConsumerUniV2`, since we only have V3 now
* Use `ParamChainName` instead of `any`
* Use `ethers.utils` instead of `hre.ethers.utils` to avoid type errors
=> fix: remove Uniswap V2 token consumer from messaging deploy task

packages/tasks/templates/omnichain/tasks/deploy.ts.hbs
Display URLs both for ZetaScan and Blockscout both for mainnet and testnet.
=> fix: display correct explorer URL on contract deploy

packages/client/src/getPools.ts, packages/tasks/src/pools.ts
- fix: make queries to the right RPC
- fix: decimals
```
┌────────────────────────────────────────────┬────────────────────┬─────────────────────────┐
│                  (index)                   │        Pool        │        Reserves         │
├────────────────────────────────────────────┼────────────────────┼─────────────────────────┤
│ 0x0C0B35C5eF00d9caD8D2ce65b147ea2A27d526Bc │ 'BTC.BTC / WZETA'  │   '2.89 / 144372.85'    │
│ 0x16Ef1b018026E389FDA93c1e993E987CF6E852E7 │ 'WZETA / ETH.ETH'  │   '222552.62 / 90.93'   │
│ 0x4E77A430a1b8E9055540b2A4aB8364E4E31089ae │ 'BNB.BSC / WZETA'  │  '576.06 / 261228.28'   │
│ 0x10B4De1dE9dC1b5B66bbce613f56CABbAfD1Ef4c │ 'USDC.BSC / WZETA' │  '35546.43 / 26529.58'  │
│ 0xC9D3BA9e55958f316cbB81FAD70c2608810124a6 │ 'WZETA / USDT.BSC' │  '30993.55 / …
```
=> fix: pools querying on mainnet

contracts/shared/MockSystemContract.sol
For certain scenarios, we need to obtain the `origin` address, such as the Staking contract in the Example contract, therefore we need to add an `origin` address parameter.
=> feat: Add origin address for MockSystemContract

contracts/SwapHelperLib.sol, packages/tasks/templates/omnichain/contracts/{{contractName}}.sol.hbs
* Rename `_doSwap` to `swapExactTokensForTokens`
* Pass the system contract directly to swap function to avoid repetitive code in tutorials
* Removed `immutable` from the system contract var so that it can be used to instantiate variables in the constructor (throws an error otherwise)
Passing the system contract directly will allow us to do something like this:
```solidity
import "@zetachain/protocol-contracts/contracts/zevm/SystemContract.sol";
import "@zetachain/protocol-contracts/contracts/zevm/interfaces/zContract.sol";
import "@zetachain/toolkit/contracts/SwapHelperLib.sol";
import "@zetachain/toolkit/contracts/BytesHelperLib.sol";
import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
contract Swap is zContract { …
```
=> feat: update swap helpers to accept system contract as argument

packages/tasks/src/deposit.ts
To allow sending failing transactions, which is useful for demo purposes.
We're using it here:
https://www.zetachain.com/docs/developers/omnichain/transactions/#usdc-to-erc-20-custody-contract-with-a-message
To show an example of a transaction that's failing:
```
npx hardhat deposit --amount 1 --network sepolia_testnet --erc20 0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238 --message '[["string"], ["hello"]]' --recipient 0x4955a3F38ff86ae92A914445099caa8eA2B9bA32 --ignore-checks
```
(just realized that I shouldn't have used it before it's shipped, but alright 😁, it's supposed to fail anyways)
=> feat(deposit): add ignore check flag

contracts/OnlySystem.sol
`OnlySystem` modifier which can be imported into contracts and used like so:
```solidity
import "@zetachain/protocol-contracts/contracts/zevm/SystemContract.sol";
import "@zetachain/protocol-contracts/contracts/zevm/interfaces/zContract.sol";
import "@zetachain/toolkit/contracts/SwapHelperLib.sol";
import "@zetachain/toolkit/contracts/BytesHelperLib.sol";
import "@zetachain/toolkit/contracts/OnlySystem.sol";
contract Swap is zContract, OnlySystem {
SystemContract public systemContract;
constructor(address systemContractAddress) {
systemContract = SystemContract(systemContractAddress);
}
function onCrossChainCall(
zContext calldata context,
address zrc20,
uint256 amount,
bytes calldata message
) external virtual override …
```
=> OnlySystem modifier

contracts/OnlySystem.sol, packages/tasks/templates/omnichain/contracts/{{contractName}}.sol.hbs
* `OnlySystem` modifier accepts a system contract (not just address)
* Omnichain template now comes with `OnlySystem` by default
New default template:
```solidity
import "@zetachain/protocol-contracts/contracts/zevm/SystemContract.sol";
import "@zetachain/protocol-contracts/contracts/zevm/interfaces/zContract.sol";
import "@zetachain/toolkit/contracts/OnlySystem.sol";
contract Swap is zContract, OnlySystem {
SystemContract public systemContract;
constructor(address systemContractAddress) {
systemContract = SystemContract(systemContractAddress);
}
function onCrossChainCall(
zContext calldata context,
address zrc20,
uint256 amount,
bytes calldata message
) external virtual override onlySystem(systemContract) {
(address targetToken, …
```
=> feat: generate omnichain contracts with new OnlySystem by default

packages/tasks/templates/messaging/contracts/{{contractName}}.sol.hbs, packages/tasks/templates/messaging/tasks/deploy.ts.hbs
Simplifies the messaging contract constructor by removing ZETA token address param: it is now fetched from the connector.
Before:
```solidity
contract MyContract is ZetaInteractor, ZetaReceiver {
ZetaTokenConsumer private immutable _zetaConsumer;
IERC20 internal immutable _zetaToken;
constructor(address connectorAddress, address zetaTokenAddress, address zetaConsumerAddress) ZetaInteractor(connectorAddress) {
_zetaToken = IERC20(zetaTokenAddress);
_zetaConsumer = ZetaTokenConsumer(zetaConsumerAddress);
}
```
After:
```solidity
import "@zetachain/protocol-contracts/contracts/evm/ZetaConnector.base.sol";
contract MyContract is ZetaInteractor, ZetaReceiver {    
ZetaTokenConsumer private immutable _zetaConsumer;
IERC20 internal immutable _zetaToken;
constructor(address connectorAddress, …
```
=> refactor(messaging): fetch zeta token address from connector

package.json, packages/test/src/index.ts, packages/test/src/test.helpers.ts
Move toolkit/test/test.helpers.ts into toolkit/packages, so that external projects can directly rely on the testing methods inside.
=> refactor: move test dir to packages

packages/test/src/helpers.ts
Reduce the amount of added liquidity to prevent scripts from running with too much ETH and not being able to complete tests.
=> refactor: update liquidity amount

package.json, packages/client/src/getPools.ts, packages/tasks/src/pools.ts
* Return all ZRC-20/ZRC-20 and ZRC-20/WZETA pools ignoring others
* Removed `toFixed(2)` to show all decimals
=> feat(pools): speed up cmd by only querying relevant zrc20 pools

packages/tasks/templates/messaging/contracts/{{contractName}}.sol.hbs, packages/tasks/templates/messaging/tasks/deploy.ts.hbs
Reverting back to setting ZETA token address explicitly through a constructor argument, instead of reading it from the connector, because connector on Ethereum and BNB has ZETA token address stored in `zetaToken`, and connector on ZetaChain has ZETA token address stored in `WZETA` (https://github.com/zeta-chain/protocol-contracts/issues/158) Thus, we can't use the same constructor to read ZETA token address, so we have to revert back to passing it explicitly.
Tested messaging to and from ZetaChain, it works.
https://zetachain-athens-3.blockscout.com/address/0xf401596Ff974F379cE85F727D2F2dc441a319e06?tab=logs
https://sepolia.etherscan.io/address/0x08b6C291B45949A2ab646C1969493913F1771DFc#events
=> fix: set ZETA token address from constructor argument

packages/tasks/templates/omnichain/tasks/interact.ts.hbs
* throw an error if the input amount is less than the refund fee. It's generally a good practice to send only amounts that can be refunded to prevent loss of funds.
* renamed the optional argument from `--token` to `--erc20` to be more explicit in what it represents
* updated param and task descriptions
We cannot add withdraw fee check as not all universal apps use withdraw. This is something devs will add themselves.
=> feat: check refund fee in omnichain interact task

packages/client/src/getFees.ts
Polygon Amoy has been added as a supported chain, but CCM hasn't been enabled for it, so `getFees` was throwing an error.
=> fix: getFees should skip querying CCM fees if chain doesn't support it

packages/client/src/zetachainWithdraw.ts
Solana:
```
npx hardhat zetachain-withdraw --amount 0.1 --zrc20 0x4955a3F38ff86ae92A914445099caa8eA2B9bA32 --receiver EnGmXjAuSd4j4ru3cSjUoBe2sT4gfNwKZ9jfoxjGs4ad --gateway-zeta-chain 0x6c533f7fe93fae114d0954697069df33c9b74fd7 --network zeta_testnet
```
https://zetachain-athens.blockpi.network/lcd/v1/public/zeta-chain/crosschain/inboundHashToCctxData/0x47c6c081c0cd5d84bde462462dcdfd21df76851fd0e32a3ef6231c6d6008878d
EVM:
```
npx hardhat zetachain-withdraw --amount 0.1 --zrc20 0x777915D031d1e8144c90D025C594b3b8Bf07a08d --receiver 0x4955a3F38ff86ae92A914445099caa8eA2B9bA32 --gateway-zeta-chain 0x6c533f7fe93fae114d0954697069df33c9b74fd7 --network zeta_testnet
```
https://zetachain-athens.blockpi.network/lcd/v1/public/zeta-chain/crosschain/inboundHashToCctxData/0x2d81a1220bb8ffb2b6a12721a7c141 …
=> fix: solana withdraw

packages/commands/src/bitcoin/depositAndCall.ts, packages/commands/src/bitcoin/index.ts, packages/commands/src/bitcoin/inscription.ts
```
yarn zetachain bitcoin inscription -r 0x11998e1A5D2e770753263376ceE78B14c9617f16 -t string -v hello -a tb1qw9tydqfkhcnl2f2m0m0xus3h90s9zd6zj7rhs8 --amount 0.0001 --private-key c7eba6bc03dbb0ffaee88ce911a55e15592499f1733c46fbef2c7f780f7737d6
```
```
Commit TXID: bbb838c636c890b948091ede71de447e47236f20a3cb4bed13982e2fc7f97e35
Reveal TXID: 53b40e206f1fa73a43e625da43a229a3321ff62aa578cc553b1d49338b674055
```
https://mempool.space/signet/tx/bbb838c636c890b948091ede71de447e47236f20a3cb4bed13982e2fc7f97e35
https://mempool.space/signet/tx/53b40e206f1fa73a43e625da43a229a3321ff62aa578cc553b1d49338b674055
https://zetachain-athens.blockpi.network/lcd/v1/public/zeta-chain/crosschain/inboundHashToCctxData/bbb838c636c890b948091ede71de447e47236f20a3cb4bed13982e2fc7f97e35 …
=> feat: sending Bitcoin inscriptions
